import re


def normalize_code_text(text):
    """Очистка текста от артефактов OCR и приведение к Python-синтаксису."""
    if not text:
        return ""

    # Исправление кириллических символов, похожих на латинские
    replacements = {
        'х': 'x', 'Х': 'X', 'у': 'y', 'У': 'Y', 'а': 'a', 'А': 'A',
        'е': 'e', 'Е': 'E', 'о': 'o', 'О': 'O', 'р': 'p', 'Р': 'P',
        'с': 'c', 'С': 'C', 'т': 't', 'Т': 'T', 'В': 'B'
    }
    for rus, lat in replacements.items():
        text = text.replace(rus, lat)

    # Исправление операторов
    text = text.replace("—", "-").replace("–", "-")
    text = text.replace("=z", "==").replace("==", "==")
    text = text.replace("“", '"').replace("”", '"').replace("‘", "'").replace("’", "'")
    text = text.replace("нет", "!=").replace("да", "==")

    # Убираем лишние переносы и двойные пробелы
    text = re.sub(r'\s+', ' ', text).strip()

    return text


def generate_smart_code(elements, connections):
    """
    Генерирует связный Python код на основе распознанных блоков и их связей.
    elements: список словарей с 'label', 'text', 'bbox'
    connections: список кортежей (индекс_откуда, индекс_куда)
    """

    # 1. Строим граф связей (список смежности)
    adj = {i: [] for i in range(len(elements))}
    for f, t in connections:
        if f < len(elements) and t < len(elements):
            adj[f].append(t)

    code_lines = ["# Generated by Flowchart2Code", "def main():"]
    visited = set()

    def walk(idx, indent=1):
        if idx in visited:
            return
        visited.add(idx)

        el = elements[idx]
        label = el.get('label', 'rect')
        raw_text = el.get('text', '')
        text = normalize_code_text(raw_text)

        spaces = "    " * indent
        outputs = adj[idx]

        # ЛОГИКА ДЛЯ РОМБА (УСЛОВИЕ)
        if label == 'diamond':
            condition = text if text else "True"
            code_lines.append(f"{spaces}if {condition}:")

            if len(outputs) > 0:
                walk(outputs[0], indent + 1)
            else:
                code_lines.append(f"{spaces}    pass")

            if len(outputs) > 1:
                code_lines.append(f"{spaces}else:")
                walk(outputs[1], indent + 1)

        # ЛОГИКА ДЛЯ ШЕСТИУГОЛЬНИКА (ЦИКЛ ИЛИ ПОДГОТОВКА)
        elif label == 'hexagon':
            # Если текст похож на range или условие цикла
            if "in" in text or "range" in text:
                code_lines.append(f"{spaces}for {text}:")
                for nxt in outputs:
                    walk(nxt, indent + 1)
            else:
                code_lines.append(f"{spaces}# Setup: {text}")
                code_lines.append(f"{spaces}{text}")
                for nxt in outputs:
                    walk(nxt, indent)

        # ЛОГИКА ДЛЯ ЭЛЛИПСА (НАЧАЛО/КОНЕЦ)
        elif label == 'ellipse':
            if "конец" in text.lower() or "end" in text.lower():
                code_lines.append(f"{spaces}return # {text}")
            else:
                code_lines.append(f"{spaces}# Start: {text}")
                for nxt in outputs:
                    walk(nxt, indent)

        # ЛОГИКА ДЛЯ КВАДРАТА (ДЕЙСТВИЕ)
        else:
            if text:
                # Если текст выглядит как вывод (YES/NO или просто строка)
                if text.upper() in ["YES", "NO", "ДА", "НЕТ"]:
                    code_lines.append(f"{spaces}print('{text}')")
                else:
                    code_lines.append(f"{spaces}{text}")

            for nxt in outputs:
                walk(nxt, indent)

    # Запуск обхода с первого элемента (обычно это начало схемы)
    if elements:
        walk(0)
    else:
        code_lines.append("    pass")

    code_lines.append(f"\nif __name__ == '__main__':\n    main()")
    return "\n".join(code_lines)

# Пример использования:
# result_python = generate_smart_code(detected_blocks, found_connections)
# print(result_python)